#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-cert
  namespace: tanzu-system-ingress
spec:
  commonName: #@ "*.cnrs.{}".format(data.values.domain)
  dnsNames:
  - #@ "*.cnrs.{}".format(data.values.domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: #@ "{}".format(data.values.letsencrypt.issuer)
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - Mathias Ewald
  renewBefore: 360h0m0s
  secretName: tap-cert
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-cert-delegation
  namespace: tanzu-system-ingress
spec:
  delegations:
    - secretName: tap-cert
      targetNamespaces:
        - "*"
