#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: cert-manager
data:
  key.json: #@ base64.encode(data.values.cloudDNS.key)
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: #@ data.values.letsencrypt.email
    privateKeySecretRef: 
      name: letsencrypt-staging-dns-account-key
    solvers:
      - dns01:
          cloudDNS:
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
            project: cso-pcfs-emea-mewald
        selector:
          dnsZones:
          - #@ data.values.domain

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: #@ data.values.letsencrypt.email
    privateKeySecretRef: 
      name: letsencrypt-staging-dns-account-key
    solvers:
      - dns01:
          cloudDNS:
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
            project: cso-pcfs-emea-mewald
        selector:
          dnsZones:
          - #@ data.values.domain
