#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"PackageInstall", "metadata":{"name":"cnrs"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: cnrs-network-config-overlay

---
apiVersion: v1
kind: Secret
metadata:
  name: cnrs-network-config-overlay
stringData:
  cnrs-network-config-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"metadata":{"name":"config-network"}, "kind": "ConfigMap"})
    ---
    data:
      #@overlay/match missing_ok=True
      default-external-scheme: https
      #@overlay/match missing_ok=True
      auto-tls: Enabled
      #@overlay/match missing_ok=True
      http-protocol: Redirected
