---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-objects-reader
  namespace: service-instances
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sql-objects-reader
  namespace: service-instances
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sql-objects-reader
subjects:
- kind: ServiceAccount
  name: sql-objects-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sql-objects-reader
  namespace: service-instances
rules:
- apiGroups:     [ "" ]
  resources:     [ "secrets" ]
  verbs:         &objReaderVerbs [ "get", "list", "watch" ]
- apiGroups:     [ "sql.cnrm.cloud.google.com" ]
  resources:     [ "sqlinstances", "sqldatabases", "sqlusers" ]
  verbs:         *objReaderVerbs
