#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: #@ data.values.name
  namespace: service-instances
spec:
  inputResources:
  - name: sqlInstance
    ref:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLInstance
      name: #@ data.values.instance_name
  - name: sqlDatabase
    ref:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLDatabase
      name: #@ data.values.database_name
  - name: sqlUser
    ref:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLUser
      name: #@ data.values.user_name
  - name: sqlUserSecret
    ref:
      apiVersion: v1
      kind: Secret
      name: $(.sqlUser.spec.password.valueFrom.secretKeyRef.name)
  serviceAccountName: sql-objects-reader
  template:
    data:
      password: $(.sqlUserSecret.data.password)
    metadata:
      labels:
        app.kubernetes.io/component: cloudsql-postgres
        app.kubernetes.io/instance: "$(.sqlInstance.metadata.name)"
        services.apps.tanzu.vmware.com/class: #@ data.values.service_class
    stringData:
      database: $(.sqlDatabase.metadata.name)
      host: $(.sqlInstance.status.publicIpAddress)
      port: "5432"
      type: postgresql
      username: $(.sqlUser.metadata.name)
