#@ load("@ytt:data", "data")
---
kind: Password
apiVersion: secretgen.k14s.io/v1alpha1
metadata:
  name: #@ data.values.name
  namespace: service-instances
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      password: #@ data.values.password
