---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: petclinic
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
  name: petclinic
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: ORG_SPRINGFRAMEWORK_CLOUD_BINDINGS_BOOT_ENABLE
    value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims: 
  - name: database 
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: petclinic-postgres
  source:
    git:
      ref:
        branch: main
      url: https://github.com/mathias-ewald/spring-petclinic.git


