#@data/values
---
tanzunet:
  username: "mathiase@vmware.com"
  password: "*******************"

container_registry:
  username: "_json_key"
  password: "*******************"

cloudDNS:
  key: "****************"  

github:
  clientId: "**************"
  clientSecret: "**************"

database:
  host: "***************"
  database: "***************"
  username: "***************"
  password: "***************"
