---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-full-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access
subjects:
- kind: ServiceAccount
  name: dev-user
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: dev-user-token
  annotations:
    kubernetes.io/service-account.name: dev-user
