#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: #@ "{}-token".format(data.values.sa)
  namespace: #@ data.values.namespace
  annotations:
    kubernetes.io/service-account.name: #@ data.values.sa
